version: '3'

volumes:
  pg_data_production:
  static_volume:
  user_files:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: hashut/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    env_file: .env
    build: hashut/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: hashut/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
    ports:
      - 9000:80