FROM python:3.9

WORKDIR /app

RUN pip install gunicorn==20.1.0

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

# При старте контейнера запустить сервер разработки.
# Ключ --bind 0.0.0.0:8000 привяжет приложение к порту 8000, доступному извне
CMD ["gunicorn", "--bind", "0.0.0.0:9000", "backend.wsgi"]
